### ISSUE TITLE
"Custom biome generators be stored in a config file"

### ISSUE THREAD

**Issue by MichaelHilus** [rutgerkok/WorldGeneratorApi#14]
**Describe the bug**
When a world with a custom biome generator is about to be stored, the server crashes with `UnsupportedOperationException: Custom biome generators be stored in a config file`.

**To Reproduce**
1. Create a biome generator like in the examples that sets everywhere the biome to `DESERT`.
2. Use the `WorldGeneratorInitEvent` approach to set your generator: `event.getWorldGenerator().setBiomeGenerator(new CustomBiomeGenerator())`
3. Use Multiverse to generate a new world
4. Fly around the world
5. Stop the server

The exception raises whenever the world is going to be persisted. This happens eigher while flying around, or at server stop. I could too find this exception raised when deleting the world with `/mv delete <yourworld>`.

**Comment by MichaelHilus** [comment]
While digging in `WorldGeneratorApi`s code, I found that the `InjectedBiomeGenerator.a()` method is throwing that exception by default. So will this method not be called when using a config file? If so, can this be fixed with an empty config file, or are there some required properties that need to be placed in that file?

**Comment by rutgerkok** [comment]
For some reason, I cannot reproduce this. I tried it as you described, with Multiverse and a plugin that uses the WorldGeneratorIntEvent. However, Minecraft never calls this `.a()` method and just saves the world with the default biome generator stored in the level.dat.

Maybe it depends on the custom settings of your world? Do you have a stack trace?

**Comment by rutgerkok** [comment]
Happens on Spigot too... I'll try to see if I can come up with something in the Bukkit API that breaks because the WorldInitEvent is fired too late. If yes, then I can submit a valid bug report to them.

**Comment by RomainStorai** [comment]
Hey I got the same problem, step to reproduce: generate few chunks with a custom biome generator and the call World#save.
I hope you'll be able to test it cause this is a problem when it comes to save generated world

**Comment by rutgerkok** [comment]
So that means that the latest dev build ( https://ci.codemc.io/job/rutgerkok/job/WorldGeneratorApi/ ) doesn't fix the issue?

If not, I'll try that!

**Comment by RomainStorai** [comment]
Not tested yet, i'll tell you more today

**Comment by RomainStorai** [comment]
Update: The old error is now replace with a cast error.
https://prnt.sc/tlhgf2
c.f. issue opened

**Comment by rutgerkok** [comment]
Second attempt! Build 11 (available soon) at https://ci.codemc.io/job/rutgerkok/job/WorldGeneratorApi/ should fix this.
